name       : pioneer
version    : '20170415'
release    : 3
source     :
    - https://github.com/pioneerspacesim/pioneer/archive/20170415.tar.gz : dfbcfb63686fa3b7a16a4bac34de81adb02eeaf23593b3e63cca906bf4dbef67
license    :
    - Apache-2.0
    - CC-BY-SA-3.0
    - GPL-3.0
    - NASA-1.3
    - SIL-1.1
component  : games.action
summary    : Pioneer is a space adventure game set in the Milky Way galaxy at the turn of the 31st century.
description: |
    Pioneer is a space adventure game set in the Milky Way galaxy at the turn of the 31st century.
builddeps  :
    - pkgconfig(assimp)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(vorbisfile)
setup      : |
    ./bootstrap
    export PIONEER_DATA_DIR=/usr/share/pioneer
    %configure
build      : |
    %make
install    : |
    %make_install
    for px in 16 22 24 32 40 48 64 128 256; do
        install -D -m00644 application-icon/pngs/pioneer-${px}x${px}.png $installdir/usr/share/icons/hicolor/${px}x${px}/apps/pioneer.png
    done
    install -D -m00644 $pkgfiles/pioneer.desktop $installdir/usr/share/applications/pioneer.desktop
