name       : pioneer
version    : '20210203'
release    : 13
source     :
    - https://github.com/pioneerspacesim/pioneer/archive/refs/tags/20210203.tar.gz : fcbc57374123b44161e9d15d97bd950255f654a222840894f50bfc2be716ea68
license    :
    - Apache-2.0
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
    - NASA-1.3
    - OFL-1.1
component  : games.action
summary    : Pioneer is a space adventure game set in the Milky Way galaxy at the turn of the 31st century
description: |
    Pioneer is a space adventure game set in the Milky Way galaxy at the turn of the 31st century.
builddeps  :
    - pkgconfig(assimp)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(SDL2_image)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(vorbisfile)
    - pkgconfig(x11)
setup      : |
    %cmake -DPIONEER_DATA_DIR=/usr/share/pioneer .
build      : |
    %make
    %make build-data
install    : |
    %make_install
    for px in 16 22 24 32 40 48 64 128 256; do
        install -D -m00644 application-icon/pngs/pioneer-${px}x${px}.png $installdir/usr/share/icons/hicolor/${px}x${px}/apps/pioneer.png
    done
