name       : pioneer
version    : '20190203'
release    : 7
source     :
    - https://github.com/pioneerspacesim/pioneer/archive/20190203.tar.gz : e526f1659ae321f45b997c0245acecbf9c4cf2122b025ab8db1090f1b9804f5e
license    :
    - Apache-2.0
    - CC-BY-SA-3.0
    - GPL-3.0-or-later
    - NASA-1.3
    - OFL-1.1
component  : games.action
summary    : Pioneer is a space adventure game set in the Milky Way galaxy at the turn of the 31st century
description: |
    Pioneer is a space adventure game set in the Milky Way galaxy at the turn of the 31st century.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(lua-5.1)
    - pkgconfig(SDL2_image)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(vorbisfile)
    - assimp-devel
setup      : |
    %cmake -DPIONEER_DATA_DIR=/usr/share/pioneer .
build      : |
    %make
install    : |
    %make_install
    for px in 16 22 24 32 40 48 64 128 256; do
        install -D -m00644 application-icon/pngs/pioneer-${px}x${px}.png $installdir/usr/share/icons/hicolor/${px}x${px}/apps/pioneer.png
    done
